[package]
name = "pocket"
version = "0.1.0"
authors = ["James Taylor <jamestaylor3@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
clap = "~2.27.0"